version: '2'

services:
    app:
        build:
            context: .
            args:
                GOLANG_VERSION: ${GOLANG_VERSION}
                DEPLOYMENT_PATH: ${DEPLOYMENT_PATH}
                TIMEZONE: ${TIMEZONE}
        ports:
            - "${APP_PORT_EXPOSE}:9696"
